Repository Codeit-Sprint-short-track/Slid-to-Do, pull requests merged in 2024-07, with the labels that each got.

#2 Update README.md
  README.md
Labels: 📃 document

#8 [Kan-20] Feature: router 작업
  .eslintrc
  src/App.tsx
  src/constants/routes.ts
  src/index.tsx
  src/pages/DashboardPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/router.tsx
Labels: 🌏 page, ⚙️ setting

#11 [Kan-63] Chore: 폴더 구조 변경
  .husky/commit-msg
  .husky/pre-commit
  README.md
  src/components/SideBar/index.tsx
  src/pages/Dashboard/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/signUp/index.tsx
  src/router.tsx
Labels: 📃 document

#10 [KAN-24] Feature: 팝업
  .storybook/main.ts
  .storybook/preview-head.html
  .storybook/preview.ts
  package-lock.json
  package.json
  src/assets/delete.svg
  src/assets/index.ts
  src/components/Popup/index.stories.tsx
  src/components/Popup/index.tsx
Labels: ✨ component

#13 [KAN-21] Feature: Button Component 구현 및 스토리북 적용
  .eslintrc
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/components/Button/index.stories.tsx
  src/components/Button/index.tsx
  src/components/Popup/index.tsx
  src/components/SideBar/index.tsx
  src/router.tsx
  src/utils/cn.ts
  tailwind.config.js
  tmp/tmp.ts
  tsconfig.paths.json
Labels: ✨ component

#12 [Kan-64] Fix: 팝업 수정
  .eslintrc
  src/components/Popup/index.stories.tsx
  src/components/Popup/index.tsx
Labels: ✨ component

#14 [Kan-26] Feature: 로그인 페이지 퍼블리싱
  src/pages/SignIn/index.tsx
Labels: 🌏 page

#15 [KAN-27] Feature: 회원가입 페이지 퍼블리싱
  src/pages/signUp/index.tsx
Labels: 🌏 page

#16 [Kan-65] Feature: 사이드바 버튼 컴포넌트 적용 및 디자인 수정
  src/assets/flag.svg
  src/assets/home.svg
  src/assets/index.ts
  src/assets/plus.svg
  src/components/SideBar/index.tsx
Labels: ✨ component

#18 [KAN-66] Feaure: Input 컴포넌트, Form 예시
  .eslintrc
  package-lock.json
  package.json
  src/assets/index.ts
  src/assets/visibilityOff.svg
  src/assets/visibilityOn.svg
  src/components/Button/index.tsx
  src/components/Input/BaseInput/Example.tsx
  src/components/Input/BaseInput/index.stories.tsx
  src/components/Input/BaseInput/index.tsx
  src/components/Input/PasswordInput/index.stories.tsx
  src/components/Input/PasswordInput/index.tsx
  src/styles/inputVariants.ts
Labels: ✨ component

#17 [Kan-23] Feature: 투두리스트
  src/assets/activeBlue.svg
  src/assets/file.svg
  src/assets/goal.svg
  src/assets/inactive.svg
  src/assets/index.ts
  src/assets/link.svg
  src/assets/noteView.svg
  src/assets/noteWrite.svg
  src/components/TodoList/index.stories.tsx
  src/components/TodoList/index.tsx
  src/types/interface.ts
  tsconfig.paths.json
Labels: ✨ component

#19 [Kan-62] Feature: Kebab 컴포넌트 구현
  .eslintrc
  src/assets/index.ts
  src/assets/kebab.svg
  src/components/Kebab/index.stories.tsx
  src/components/Kebab/index.tsx
  src/utils/useOutsideClick.ts
  tailwind.config.js
Labels: ✨ component

#20 [KAN-69] Feature: 사이드바 스토리북
  src/components/SideBar/index.stories.tsx
Labels: ✨ component

#23 Fix: 투두리스트 높이
  src/components/TodoList/index.tsx
Labels: ✨ component

#22 [Kan-56] Feature: note list page 퍼블리싱
  src/assets/flag.svg
  src/assets/index.ts
  src/assets/noteList.svg
  src/constants/routes.ts
  src/pages/Notes/components/NoteList/NoteItem.tsx
  src/pages/Notes/components/NoteList/index.tsx
  src/pages/Notes/index.tsx
  src/router.tsx
  src/types/interface.ts
Labels: ✨ component, 🌏 page

#21 [Kan-68] Feature: 사이드바 반응형 UI 작업
  src/App.tsx
  src/assets/hamburger.svg
  src/assets/index.ts
  src/assets/plus.svg
  src/components/Kebab/index.tsx
  src/components/SideBar/DesktopSideBar.tsx
  src/components/SideBar/DesktopSideBarContents.tsx
  src/components/SideBar/MobileSideBar.tsx
  src/components/SideBar/MobileSideBarContents.tsx
  src/components/SideBar/index.tsx
  src/hooks/useOutsideClick.ts
  src/hooks/useWindowWidth.ts
  src/pages/SignUp/index.tsx
  src/router.tsx
Labels: ✨ component, 🌏 page

#27 [KAN-75] Chore: github 워크플로우 수정
  .eslintignore
  .github/workflows/feature-check.yaml
  .github/workflows/main-check.yaml
  .prettierignore
  package.json
Labels: ⚙️ setting

#25 [KAN-51] Feature: 대쉬보드 페이지
  .vscode/settings.json
  src/assets/arrowDown.svg
  src/assets/arrowRight.svg
  src/assets/arrowUp.svg
  src/assets/flag.svg
  src/assets/index.ts
  src/assets/plus.svg
  src/assets/progress.svg
  src/assets/progressEllipse.svg
  src/assets/todoRecently.svg
  src/components/TodoList/index.tsx
  src/constants/routes.ts
  src/pages/Dashboard/components/MyProgress/index.tsx
  src/pages/Dashboard/components/RecentTodos/index.tsx
  src/pages/Dashboard/components/TodosByGoal/TodoSection.tsx
  src/pages/Dashboard/components/TodosByGoal/TodosByGoalBox.tsx
  src/pages/Dashboard/components/TodosByGoal/index.tsx
  src/pages/Dashboard/components/mockData.ts
  src/pages/Dashboard/index.tsx
  src/router.tsx
  src/types/interface.ts
Labels: ✨ component, 🌏 page

#24 [Kan-35] Feature: 할일 상세 모달
  src/assets/activeWhite.svg
  src/assets/arrowDropdown.svg
  src/assets/grayDelete.svg
  src/assets/index.ts
  src/components/LinkModal/index.tsx
  src/components/TodoList/index.stories.tsx
  src/components/TodoModal/Dropdown.tsx
  src/components/TodoModal/FilePreview.tsx
  src/components/TodoModal/FileUploadButton.tsx
  src/components/TodoModal/GoalSection.tsx
  src/components/TodoModal/LinkCard.tsx
  src/components/TodoModal/LinkUploadButton.tsx
  src/components/TodoModal/StatusSection.tsx
  src/components/TodoModal/TitleSection.tsx
  src/components/TodoModal/TodoDetailModal/index.stories.tsx
  src/components/TodoModal/TodoDetailModal/index.tsx
  src/components/TodoModal/TodoDetailModal/useTodoDetail.ts
  src/constants/regex.ts
Labels: ✨ component

#26 [Kan-37] Feature: 모든 할 일 페이지
  package-lock.json
  src/assets/index.ts
  src/assets/plusBlue.svg
  src/components/Toast/index.tsx
  src/components/TodoList/TodoItem.tsx
  src/components/TodoList/index.tsx
  src/constants/routes.ts
  src/hooks/useWindowHeight.ts
  src/pages/Todos/components/FilterButtons/FilterButton.tsx
  src/pages/Todos/components/FilterButtons/index.tsx
  src/pages/Todos/index.tsx
  src/pages/Todos/mockNotes.ts
  src/pages/Todos/mockTodos.ts
  src/router.tsx
Labels: ✨ component, 🌏 page

#29 Docs: Update README.md
  README.md
Labels: 📃 document

#28 [KAN-59] Feature: publish goal detail page
  .vscode/settings.json
  src/App.tsx
  src/assets/index.ts
  src/assets/note.svg
  src/constants/routes.ts
  src/pages/GoalDetail/components/GoalBox/index.tsx
  src/pages/GoalDetail/components/TodoBox/index.tsx
  src/pages/GoalDetail/index.tsx
  src/pages/GoalDetail/mockData.ts
  src/router.tsx
Labels: ✨ component, 🌏 page

#31 Chore: tailwind default theme 적용
  .eslintignore
  tailwind.config.js
Labels: ⚙️ setting

#32 [Kan-76] Fix: 사이드바 UI 수정
  src/components/SideBar/DesktopSideBar.tsx
  src/components/SideBar/MobileSideBar.tsx
Labels: ✨ component

#33 [Kan-57] Feature: note detail 컴포넌트 퍼블리싱
  src/components/NoteDetail/index.tsx
  src/pages/Notes/components/NoteList/NoteItem.tsx
  src/pages/Notes/index.tsx
  src/utils/formatDate.ts
Labels: ✨ component

#34 [Kan-77] Feature: 로그인 회원가입 UI 수정 및 컴포넌트 변경
  src/components/SideBar/DesktopSideBarContents.tsx
  src/components/SideBar/MobileSideBarContents.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
Labels: 🌏 page

#35 [Kan-73] Feature: API Fetching
  .env
  package-lock.json
  package.json
  src/App.tsx
  src/app/api/axiosInstance.ts
  src/app/api/filesAPI.ts
  src/app/api/goalsAPI.ts
  src/app/api/notesAPI.ts
  src/app/api/todosAPI.ts
  src/components/LinkModal/index.tsx
  src/components/Popup/index.tsx
  src/components/Toast/index.tsx
  src/hooks/api/filesAPI/usePostFile.ts
  src/hooks/api/goalsAPI/useGetGoals.ts
  src/hooks/api/notesAPI/useGetNote.ts
  src/hooks/api/notesAPI/useGetNotes.ts
  src/hooks/api/todosAPI/useDeleteTodo.ts
  src/hooks/api/todosAPI/useGetProgress.ts
  src/hooks/api/todosAPI/useGetTodos.ts
  src/hooks/api/todosAPI/usePatchDone.ts
  src/hooks/api/todosAPI/usePatchTodo.ts
  src/hooks/api/todosAPI/usePostTodo.ts
  src/hooks/api/useApiError.ts
  src/hooks/useVisibility.ts
  tsconfig.paths.json
Labels: 📬 api

#36 [KAN-47] Feature: dashboard chart animation
  .eslintrc
  .vscode/settings.json
  package-lock.json
  package.json
  src/components/Input/BaseInput/Example.tsx
  src/pages/Dashboard/components/MyProgress/index.tsx
  src/pages/Dashboard/components/TodosByGoal/TodosByGoalBox.tsx
  src/pages/Dashboard/index.tsx
Labels: ✨ component
