Repository Codeit-Sprint-short-track/Slid-to-Do, pull requests merged in 2024-08, with the labels that each got.

#38 [Kan-45] Feature: note에서 글 작성 editor 구현
  package-lock.json
  package.json
  src/assets/alignCenter.svg
  src/assets/alignLeft.svg
  src/assets/alignRight.svg
  src/assets/bold.svg
  src/assets/bullet.svg
  src/assets/fontColor.svg
  src/assets/index.ts
  src/assets/italic.svg
  src/assets/link.svg
  src/assets/numberList.svg
  src/assets/underline.svg
  src/components/TodoList/TodoItem.tsx
  src/constants/routes.ts
  src/pages/NewNote/components/TextEditor/FontColorButton.tsx
  src/pages/NewNote/components/TextEditor/LinkButton.tsx
  src/pages/NewNote/components/TextEditor/Toolbar.tsx
  src/pages/NewNote/components/TextEditor/index.css
  src/pages/NewNote/components/TextEditor/index.tsx
  src/pages/NewNote/index.tsx
  src/router.tsx
  tailwind.config.js
Labels: ✨ component

#40 [Kan-44] Feature: note 생성 페이지 퍼블리싱
  src/App.tsx
  src/pages/NewNote/components/TextEditor/Toolbar.tsx
  src/pages/NewNote/components/TextEditor/index.css
  src/pages/NewNote/components/TextEditor/index.tsx
  src/pages/NewNote/index.tsx
  src/pages/Notes/index.tsx
Labels: 🌏 page

#41 [Kan-32] Feature: initial page setting
  src/App.tsx
  src/app/api/axiosInstance.ts
  src/components/SideBar/DesktopSideBar.tsx
  src/components/SideBar/index.tsx
Labels: 🌏 page

#43 Fix: 투두아이템, initialPageParam 수정
  src/app/api/filesAPI.ts
  src/components/TodoItem/index.stories.tsx
  src/components/TodoItem/index.tsx
  src/hooks/api/goalsAPI/useGetGoals.ts
  src/hooks/api/notesAPI/useGetNotes.ts
  src/hooks/api/todosAPI/useGetTodos.ts
  src/hooks/api/useApiError.ts
Labels: 🐞 hotfix, ✨ component, 📬 api

#44 [Kan-31] Feature: 사이드바 API 연결
  package-lock.json
  package.json
  src/components/SideBar/DesktopSideBar.tsx
  src/components/SideBar/DesktopSideBarContents.tsx
  src/components/SideBar/MobileSideBar.tsx
  src/components/SideBar/MobileSideBarContents.tsx
  src/components/SideBar/index.tsx
  src/hooks/api/goalsAPI/usePostGoal.ts
  tailwind.config.js
Labels: ✨ component

#45 [Kan-70] Chore: aws 정적 배포 자동화 구현
  .github/workflows/main-deploy.yaml
  package.json
  src/pages/NewNote/components/TextEditor/FontColorButton.tsx
Labels: ⚙️ setting

#46 [KAN-80] Feature: 첫 페이지 이동 시 로컬 스토리지 기준
  src/App.tsx
  src/components/SideBar/DesktopSideBar.tsx
  src/components/SideBar/DesktopSideBarContents.tsx
  src/components/SideBar/index.tsx
Labels: 🎨 layout

#47 [Kan-40] Feature: 할일 모달, 할일 페이지 API 연결
  package-lock.json
  package.json
  src/components/Toast/index.tsx
  src/components/TodoModal/Dropdown.tsx
  src/components/TodoModal/FileLinkSection.tsx
  src/components/TodoModal/FilePreview.tsx
  src/components/TodoModal/FileUploadButton.tsx
  src/components/TodoModal/GoalSection.tsx
  src/components/TodoModal/LinkCard.tsx
  src/components/TodoModal/TodoCreateModal/index.tsx
  src/components/TodoModal/TodoDetailModal/index.tsx
  src/components/TodoModal/TodoDetailModal/useTodoDetail.ts
  src/hooks/api/todosAPI/useGetTodos.ts
  src/pages/Todos/components/FilterButtons/FilterButton.tsx
  src/pages/Todos/index.tsx
  src/utils/getFileType.ts
Labels: ✨ component, 🌏 page, 📬 api

#51 [Kan-49] Feature: 임시 저장 로직 구현
  src/assets/check.svg
  src/assets/circleDelete.svg
  src/assets/embed.svg
  src/assets/index.ts
  src/components/NoteDetail/index.tsx
  src/components/TodoModal/FileLinkSection.tsx
  src/components/TodoModal/LinkCard.tsx
  src/pages/NewNote/components/DraftNotification/index.tsx
  src/pages/NewNote/components/DraftSavedToast/index.tsx
  src/pages/NewNote/components/Header/index.tsx
  src/pages/NewNote/components/LinkDisplay/index.tsx
  src/pages/NewNote/components/TextEditor/LinkButton.tsx
  src/pages/NewNote/components/TextEditor/Toolbar.tsx
  src/pages/NewNote/components/TextEditor/index.tsx
  src/pages/NewNote/index.tsx
  src/types/interface.ts
Labels: ✨ component, 🌏 page

#48 [KAN-46] Feature: dashboard api get
  package-lock.json
  package.json
  public/img/loading.webp
  src/components/LoadingAnimation/index.tsx
  src/pages/Dashboard/components/MyProgress/index.tsx
  src/pages/Dashboard/components/RecentTodos/index.tsx
  src/pages/Dashboard/components/TodosByGoal/TodoSection.tsx
  src/pages/Dashboard/components/TodosByGoal/TodosByGoalBox.tsx
  src/pages/Dashboard/components/TodosByGoal/ToggleButton.tsx
  src/pages/Dashboard/components/TodosByGoal/index.tsx
  src/pages/Dashboard/components/mockData.ts
  src/pages/GoalDetail/components/TodoBox/index.tsx
  src/pages/GoalDetail/index.tsx
Labels: ✨ component

#52 [Kan-50] Feature: 노트 생성, 수정 api 연결
  .eslintrc
  package-lock.json
  package.json
  src/app/api/notesAPI.ts
  src/components/NoteDetail/index.tsx
  src/components/TodoItem/index.tsx
  src/hooks/api/notesAPI/useDeleteNote.ts
  src/hooks/api/notesAPI/usePatchNote.ts
  src/hooks/api/notesAPI/usePostNote.ts
  src/pages/NewNote/components/Header/index.tsx
  src/pages/NewNote/components/InfoSection/index.tsx
  src/pages/NewNote/components/TitleInput/index.tsx
  src/pages/NewNote/index.tsx
  src/types/interface.ts
Labels: ✨ component, 🌏 page, 📬 api

#53 [Kan-58] Feature: note list 페이지 infinite scroll, api 연결
  src/components/NoteDetail/index.tsx
  src/hooks/api/goalsAPI/useGetGoal.ts
  src/hooks/api/notesAPI/useDeleteNote.ts
  src/hooks/api/notesAPI/useGetNote.ts
  src/hooks/api/notesAPI/useGetNotes.ts
  src/hooks/api/notesAPI/usePatchNote.ts
  src/hooks/api/notesAPI/usePostNote.ts
  src/pages/NewNote/index.tsx
  src/pages/Notes/components/NoteList/NoteItem.tsx
  src/pages/Notes/components/NoteList/index.tsx
  src/pages/Notes/index.tsx
  src/router.tsx
Labels: 🌏 page, 📬 api

#57 [Kan-54] Feature: 대쉬보드, 목표 상세 페이지 api
  src/components/SideBar/DesktopSideBarContents.tsx
  src/components/SideBar/MobileSideBarContents.tsx
  src/hooks/api/goalsAPI/useDeleteGoal.ts
  src/hooks/api/goalsAPI/usePatchGoal.ts
  src/pages/Dashboard/components/TodosByGoal/TodoSection.tsx
  src/pages/Dashboard/components/TodosByGoal/TodosByGoalBox.tsx
  src/pages/Dashboard/components/TodosByGoal/ToggleButton.tsx
  src/pages/Dashboard/components/TodosByGoal/index.tsx
  src/pages/GoalDetail/components/GoalBox/index.tsx
  src/pages/GoalDetail/components/TodoBox/index.tsx
  src/pages/GoalDetail/index.tsx
  src/router.tsx
Labels: ✨ component, 🌏 page

#58 [Kan-89] Feat: 사이드바 아이콘 클릭 시 대시보드 이동
  src/App.tsx
  src/components/SideBar/DesktopSideBar.tsx
Labels: ✨ component

#60 Fix: 목표 3개씩만 로딩
  src/pages/Dashboard/components/TodosByGoal/index.tsx
Labels: 🐞 hotfix

#56 [Kan-82] Refactor: 할일 모달, 페이지 리팩토링
  public/favicon.ico
  public/index.html
  src/components/LinkModal/index.tsx
  src/components/TodoModal/FileLinkSection.tsx
  src/components/TodoModal/StatusSection.tsx
  src/components/TodoModal/TitleSection.tsx
  src/components/TodoModal/TodoCreateModal/index.tsx
  src/components/TodoModal/TodoDetailModal/index.tsx
  src/constants/regex.ts
  src/pages/NewNote/components/TextEditor/LinkButton.tsx
  src/pages/NewNote/components/TextEditor/Toolbar.tsx
  src/pages/NewNote/components/TextEditor/index.tsx
  src/pages/Todos/index.tsx
  src/pages/Todos/useLayoutStyles.ts
Labels: ✨ component, 🌏 page

#59 [Kan-87] Feature: link embed 반응형 구현
  src/components/NoteDetail/index.tsx
  src/pages/NewNote/components/Header/index.tsx
  src/pages/NewNote/components/LinkEmbed/index.tsx
  src/pages/NewNote/components/TextEditor/Toolbar.tsx
  src/pages/NewNote/components/TextEditor/index.css
  src/pages/NewNote/components/TextEditor/index.tsx
  src/pages/NewNote/index.tsx
Labels: ✨ component

#61 Feature: 쿼리 클라이언트 위치 변경, 에러 처리 로직 변경
  package-lock.json
  package.json
  src/App.tsx
  src/utils/AppErrorBoundary.tsx
Labels: ✨ component

#62 [Kan-88] Feature: GTM(GA4) 세팅
  .env
  package-lock.json
  package.json
  src/App.tsx
  src/components/LinkModal/index.tsx
  src/components/Popup/index.tsx
  src/pages/Todos/index.tsx
Labels: ⚙️ setting

#64 Feature: 사이드바 피드백 반영
  src/app/api/goalsAPI.ts
  src/components/SideBar/DesktopSideBar.tsx
  src/components/SideBar/DesktopSideBarContents.tsx
  src/components/SideBar/MobileSideBar.tsx
  src/components/SideBar/MobileSideBarContents.tsx
  src/components/SideBar/index.tsx
  src/hooks/api/goalsAPI/useGetGoals.ts
Labels: ✨ component

#65 [Kan-84] Refactor: note작성 페이지
  .husky/pre-commit
  src/components/FlagBoxIcon/index.tsx
  src/components/Kebab/index.tsx
  src/components/NoteDetail/index.tsx
  src/components/TodoItem/index.tsx
  src/constants/regex.ts
  src/hooks/useDraft.ts
  src/pages/Dashboard/components/TodosByGoal/TodosByGoalBox.tsx
  src/pages/Dashboard/components/TodosByGoal/index.tsx
  src/pages/GoalDetail/components/GoalBox/index.tsx
  src/pages/NewNote/components/InfoSection/index.tsx
  src/pages/NewNote/components/TitleInput/index.tsx
  src/pages/NewNote/index.tsx
  src/pages/Notes/index.tsx
  src/types/interface.ts
  src/utils/countHtmlCharacters.ts
Labels: ✨ component

#70 Fix: recent todos keydown
  src/components/TodoItem/index.tsx
Labels: ✨ component

#68 Refactor: todo list rendering
  src/app/api/todosAPI.ts
  src/components/TodoItem/index.tsx
  src/hooks/api/goalsAPI/useGetGoals.ts
  src/hooks/api/todosAPI/useGetProgress.ts
  src/hooks/api/todosAPI/useGetRecentTodos.ts
  src/hooks/api/todosAPI/useGetTodos.ts
  src/hooks/api/todosAPI/usePatchDone.ts
  src/pages/Dashboard/components/RecentTodos/index.tsx
  src/pages/Dashboard/components/TodosByGoal/TodoSection.tsx
  src/pages/Dashboard/components/TodosByGoal/TodosByGoalBox.tsx
  src/pages/Dashboard/components/TodosByGoal/index.tsx
  src/pages/GoalDetail/components/TodoBox/index.tsx
Labels: ✨ component

#72 Fix: todo update
  src/components/TodoModal/TodoCreateModal/index.tsx
  src/components/TodoModal/TodoDetailModal/index.tsx
  src/hooks/api/todosAPI/useDeleteTodo.ts
  src/hooks/api/todosAPI/usePatchTodo.ts
  src/hooks/api/todosAPI/usePostTodo.ts
Labels: 🐞 hotfix

#71 [Kan-83] Refactor: 사이드바 컴포넌트 분리
  src/components/SideBar/DesktopSideBar.tsx
  src/components/SideBar/DesktopSideBarContents.tsx
  src/components/SideBar/GoalList.tsx
  src/components/SideBar/Header.tsx
  src/components/SideBar/MobileSideBar.tsx
  src/components/SideBar/MobileSideBarContents.tsx
  src/components/SideBar/index.tsx
  src/hooks/useModalControl.ts
  src/hooks/usePostControl.ts
Labels: ✨ component

#67 [Kan-90] Test: 테스트, 피드백 반영
  .eslintrc
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  src/components/CreateGoalModal/GoalTitleSection.tsx
  src/components/CreateGoalModal/index.tsx
  src/components/TodoList/TodoItem.tsx
  src/components/TodoList/index.stories.tsx
  src/components/TodoList/index.tsx
  src/components/TodoModal/FileLinkSection.tsx
  src/components/TodoModal/FilePreview.tsx
  src/components/TodoModal/GoalSection.tsx
  src/components/TodoModal/LinkUploadButton.tsx
  src/components/TodoModal/TodoCreateModal/index.tsx
  src/components/TodoModal/TodoDetailModal/StatusSection.tsx
  src/components/TodoModal/TodoDetailModal/index.test.ts
  src/components/TodoModal/TodoDetailModal/index.tsx
Labels: ✨ component

#75 Fix: 사이드바 리스트 ui 수정
  src/components/SideBar/GoalList.tsx
Labels: 🐞 hotfix

#76 Fix: 투두 상태 바뀔때 깜빡임 문제 해결
  src/pages/Dashboard/components/TodosByGoal/TodoSection.tsx
  src/pages/Dashboard/components/TodosByGoal/TodosByGoalBox.tsx
  src/pages/GoalDetail/components/TodoBox/index.tsx
  src/pages/GoalDetail/index.tsx
Labels: ✨ component

#73 Feature: 노트 작성 버튼 구현
  .github/workflows/main-check.yaml
  src/App.tsx
  src/components/NoteDetail/index.tsx
  src/components/TodoItem/index.tsx
  src/components/Tooltip/index.tsx
  src/hooks/useVisibility.ts
  src/pages/NewNote/components/Header/index.tsx
  src/pages/NewNote/components/LinkDisplay/index.tsx
  src/pages/NewNote/components/TextEditor/LinkButton.tsx
  src/pages/Notes/components/NewNoteButton/TodoListModal.tsx
  src/pages/Notes/components/NewNoteButton/index.tsx
  src/pages/Notes/components/NoteList/NoteItem.tsx
  src/pages/Notes/index.tsx
  src/router.tsx
Labels: ✨ component
